- name: "Install language: 'erlang' - Install requirements"
  block:
    - name: "Install language: 'erlang' - Install requirements - UBUNTU"
      apt:
        name:
          - build-essential
          - autoconf
          - m4
          - libncurses5-dev
          - libwxgtk3.0-dev
          - libgl1-mesa-dev
          - libglu1-mesa-dev
          - libpng3
          - libssh-dev
          - unixodbc-dev
          - xsltproc
          - fop
        state: latest
        update_cache: yes
      become: yes
      when: ansible_os_family == "Debian"

    - name: "Install language: 'erlang' - Install requirements - OSX"
      homebrew:
        name:
          - autoconf
          - wxmac
        state: latest
        update_homebrew: yes
      become: no
      when: ansible_os_family == "Darwin"


- name: "Install language: 'erlang' - Add 'erlang' plugin"
  shell: ". {{ ansible_env.HOME }}/.asdf/asdf.sh && asdf plugin-add erlang"
  register: add_plugin_cmd
  failed_when: add_plugin_cmd.rc != 0 and add_plugin_cmd.rc != 2
  changed_when: add_plugin_cmd.rc != 2

- name: "Install language: 'erlang' - Install all 'erlang' versions: {{ versions }}"
  environment:
    KERL_BUILD_DOCS: yes
    KERL_CONFIGURE_OPTIONS: "--disable-debug --without-javac"
  shell: ". {{ ansible_env.HOME }}/.asdf/asdf.sh && asdf install erlang {{ version }}"
  register: install_erlang_version_cmd
  changed_when: install_erlang_version_cmd.stdout is not search('already installed')
  loop: "{{ versions }}"
  loop_control:
    loop_var: version

- name: "Install language: 'erlang' - Set global 'erlang' versions: {{ versions }}"
  shell: ". {{ ansible_env.HOME }}/.asdf/asdf.sh && asdf global erlang {{ versions | join(' ') }}"
