- name: "Install requirements - UBUNTU"
  apt:
    name:
      - automake
      - autoconf
      - libreadline-dev
      - libncurses-dev
      - libssl-dev
      - libyaml-dev
      - libxslt-dev
      - libffi-dev
      - libtool
      - unixodbc-dev
    state: latest
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: "Install requirements - MAC OSX"
  homebrew:
    name:
     - coreutils
     - automake
     - autoconf
     - openssl
     - libyaml
     - readline
     - libxslt
     - libtool
     - unixodbc
    state: latest
    update_homebrew: yes
  become: no
  when: ansible_os_family == "Darwin"

- name: "Install `asdf` - Version: {{ asdf_version }} - Checkout `asdf` to `~/.asdf`"
  git:
    repo: "git@github.com:asdf-vm/asdf.git"
    dest: "{{ ansible_env.HOME }}/.asdf"
    version: "{{ asdf_version }}"
    force: yes

- name: "Set up shell"
  import_tasks: setup-shell.yml
  when: not skip_shell_setup

- name: Load available_languages
  set_fact:
     available_languages: "{{ (lookup('fileglob', 'tasks/install-language-*.yml')).split(',') | map('basename') | map('regex_replace', 'install-language-(.*)\\.yml', '\\1') | list }}"

- name: "Install languages"
  include_tasks: install-language.yml
  vars:
    language: "{{ item.items()[0][0] }}"
    versions: "{{ item.items()[0][1] }}"
  loop: "{{ languages_to_install }}"
